export const CategoryPoints: Record<string, number> = {
  'Best Picture': 10,
  Director: 8,
  'Actor in a Leading Role': 8,
  'Actress in a Leading Role': 8,
  'Actor in a Supporting Role': 6,
  'Actress in a Supporting Role': 6,
  'Original Screenplay': 5,
  'Adapted Screenplay': 5,
  'International Feature': 4,
  'Animated Feature': 5,
  'Sound Editing': 2,
  'Visual Effects': 3,
  'Film Editing': 3,
  'Short Film, Animated': 2,
  'Short Film, Live Action': 2,
  'Documentary Short Subject': 2,
  'Original Score': 4,
  'Original Song': 3,
  'Production Design': 3,
  Cinematography: 4,
  'Costume Design': 3,
  Makeup: 3,
  'Documentary Feature': 4,
  'Sound Mixing': 2,
}

export const MobileBreak = '550px'
